# Generated by Django 3.1.1 on 2020-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('host', models.CharField(default=None, max_length=120, primary_key=True, serialize=False, verbose_name='host name')),
                ('ip', models.CharField(max_length=20, verbose_name='IP Address')),
                ('cores', models.IntegerField(verbose_name='Number of cores')),
                ('ram', models.IntegerField(verbose_name='Amount of memory')),
                ('storage', models.CharField(max_length=120, verbose_name='Total space in Giga as a list')),
                ('os_family', models.CharField(default='RedHat', max_length=20, verbose_name='OS family')),
                ('os_version', models.CharField(default='8', max_length=20, verbose_name='OS version')),
                ('system', models.CharField(default='Linux', max_length=20, verbose_name='OS Type')),
            ],
        ),
    ]
