# Generated by Django 3.1.1 on 2020-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='IP Address'),
        ),
    ]
