# Generated by Django 3.1.1 on 2020-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200910_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='os_family',
            field=models.CharField(default='RedHat', max_length=20, verbose_name='Os family'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='os_version',
            field=models.CharField(default='8', max_length=20, verbose_name='Os version'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ram',
            field=models.IntegerField(verbose_name='Amount of memory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='storage',
            field=models.CharField(max_length=120, verbose_name='Total space in Giga as a list'),
        ),
    ]
