# Generated by Django 3.1.1 on 2020-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200921_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='system',
            field=models.CharField(default='Linux', max_length=20, verbose_name='OS Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='os_family',
            field=models.CharField(default='RedHat', max_length=20, verbose_name='OS family'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='os_version',
            field=models.CharField(default='8', max_length=20, verbose_name='OS version'),
        ),
    ]
