# Generated by Django 3.1.1 on 2020-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200922_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='systemtype',
            field=models.CharField(default='PD_infra', max_length=120, verbose_name='Set system type'),
        ),
    ]
